{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "https://vault.googleapis.com/"
        }
    ],
    "info": {
        "contact": {
            "name": "Google",
            "url": "https://google.com"
        },
        "description": "Archiving and eDiscovery for G Suite.",
        "title": "G Suite Vault",
        "version": "v1",
        "x-apiClientRegistration": {
            "url": "https://console.developers.google.com"
        },
        "x-apisguru-categories": [
            "storage"
        ],
        "x-logo": {
            "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
        },
        "x-origin": [
            {
                "converter": {
                    "url": "https://github.com/lucybot/api-spec-converter",
                    "version": "2.7.31"
                },
                "format": "google",
                "url": "https://vault.googleapis.com/$discovery/rest?version=v1",
                "version": "v1"
            }
        ],
        "x-preferred": true,
        "x-providerName": "googleapis.com",
        "x-serviceName": "vault"
    },
    "tags": [
        {
            "name": "matters"
        }
    ],
    "paths": {
        "/v1/matters": {
            "get": {
                "description": "Lists matters the user has access to.",
                "operationId": "vault.matters.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "post": {
                "description": "Creates a new matter with the given name and description. The initial state\nis open, and the owner is the method caller. Returns the created matter\nwith default view.",
                "operationId": "vault.matters.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}": {
            "delete": {
                "description": "Deletes the specified matter. Returns matter with updated state.",
                "operationId": "vault.matters.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "get": {
                "description": "Gets the specified matter.",
                "operationId": "vault.matters.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "put": {
                "description": "Updates the specified matter.\nThis updates only the name and description of the matter, identified by\nmatter id. Changes to any other fields are ignored.\nReturns the default view of the matter.",
                "operationId": "vault.matters.update",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/exports": {
            "get": {
                "description": "Lists Exports.",
                "operationId": "vault.matters.exports.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "post": {
                "description": "Creates an Export.",
                "operationId": "vault.matters.exports.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/exports/{exportId}": {
            "delete": {
                "description": "Deletes an Export.",
                "operationId": "vault.matters.exports.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "get": {
                "description": "Gets an Export.",
                "operationId": "vault.matters.exports.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds": {
            "get": {
                "description": "Lists holds within a matter. An empty page token in ListHoldsResponse\ndenotes no more holds to list.",
                "operationId": "vault.matters.holds.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "post": {
                "description": "Creates a hold in the given matter.",
                "operationId": "vault.matters.holds.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds/{holdId}": {
            "delete": {
                "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
                "operationId": "vault.matters.holds.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "get": {
                "description": "Gets a hold by ID.",
                "operationId": "vault.matters.holds.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "put": {
                "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts\nto a hold that covers an OU, nor can you add OUs to a hold that covers\nindividual accounts. Accounts listed in the hold will be ignored.",
                "operationId": "vault.matters.holds.update",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds/{holdId}/accounts": {
            "get": {
                "description": "Lists HeldAccounts for a hold. This will only list individually specified\nheld accounts. If the hold is on an OU, then use\n<a href=\"https://developers.google.com/admin-sdk/\">Admin SDK</a>\nto enumerate its members.",
                "operationId": "vault.matters.holds.accounts.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "post": {
                "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that\nhas no held_org_unit set. Attempting to add an account to an OU-based\nhold will result in an error.",
                "operationId": "vault.matters.holds.accounts.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}": {
            "delete": {
                "description": "Removes a HeldAccount from a hold. If this request leaves the hold with\nno held accounts, the hold will not apply to any accounts.",
                "operationId": "vault.matters.holds.accounts.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds/{holdId}:addHeldAccounts": {
            "post": {
                "description": "Adds HeldAccounts to a hold. Returns a list of accounts that have been\nsuccessfully added. Accounts can only be added to an existing account-based\nhold.",
                "operationId": "vault.matters.holds.addHeldAccounts",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts": {
            "post": {
                "description": "Removes HeldAccounts from a hold. Returns a list of statuses in the same\norder as the request. If this request leaves the hold with no held\naccounts, the hold will not apply to any accounts.",
                "operationId": "vault.matters.holds.removeHeldAccounts",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/savedQueries": {
            "get": {
                "description": "Lists saved queries within a matter. An empty page token in\nListSavedQueriesResponse denotes no more saved queries to list.",
                "operationId": "vault.matters.savedQueries.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "post": {
                "description": "Creates a saved query.",
                "operationId": "vault.matters.savedQueries.create",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}/savedQueries/{savedQueryId}": {
            "delete": {
                "description": "Deletes a saved query by Id.",
                "operationId": "vault.matters.savedQueries.delete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            },
            "get": {
                "description": "Retrieves a saved query by Id.",
                "operationId": "vault.matters.savedQueries.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery.readonly"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}:addPermissions": {
            "post": {
                "description": "Adds an account as a matter collaborator.",
                "operationId": "vault.matters.addPermissions",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}:close": {
            "post": {
                "description": "Closes the specified matter. Returns matter with updated state.",
                "operationId": "vault.matters.close",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}:removePermissions": {
            "post": {
                "description": "Removes an account as a matter collaborator.",
                "operationId": "vault.matters.removePermissions",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}:reopen": {
            "post": {
                "description": "Reopens the specified matter. Returns matter with updated state.",
                "operationId": "vault.matters.reopen",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        },
        "/v1/matters/{matterId}:undelete": {
            "post": {
                "description": "Undeletes the specified matter. Returns matter with updated state.",
                "operationId": "vault.matters.undelete",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/ediscovery"
                        ]
                    }
                ],
                "tags": [
                    "matters"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "Oauth2": {
                "description": "Oauth 2.0 authentication",
                "type": "oauth2",
                "flows": {
                    "implicit": {
                        "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
                        "scopes": {
                            "https://www.googleapis.com/auth/ediscovery": "Manage your eDiscovery data",
                            "https://www.googleapis.com/auth/ediscovery.readonly": "View your eDiscovery data"
                        }
                    }
                }
            }
        }
    }
}